// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LMSProje.Models;

[Table("tblAuthor")]
public partial class TblAuthor
{
    [Key]
    public int AuthorId { get; set; }

    [Required]
    [StringLength(200)]
    public string AuthorName { get; set; }

    [Required]
    [StringLength(200)]
    public string AuthorLastName { get; set; }

    [InverseProperty("Author")]
    public virtual ICollection<TblBooks> TblBooks { get; set; } = new List<TblBooks>();
}