// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LMSProje.Models;

[Table("tblAdminApporoval")]
public partial class TblAdminApporoval
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("RecordID")]
    public int RecordId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime AcquisitionDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ReturnDate { get; set; }

    [Column("BookID")]
    public int BookId { get; set; }

    [ForeignKey("RecordId")]
    [InverseProperty("TblAdminApporoval")]
    public virtual TblRecords Record { get; set; }
}