// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LMSProje.Models;

[Table("tblBooks")]
public partial class TblBooks
{
    [Key]
    [Column("BookID")]
    public int BookId { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string BookName { get; set; }

    public int PageCount { get; set; }

    public int Stock { get; set; }

    public int AuthorId { get; set; }

    public int CategoryId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ProductionYear { get; set; }

    [ForeignKey("AuthorId")]
    [InverseProperty("TblBooks")]
    public virtual TblAuthor Author { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("TblBooks")]
    public virtual TblCategory Category { get; set; }

    [InverseProperty("Book")]
    public virtual ICollection<TblRecords> TblRecords { get; set; } = new List<TblRecords>();
}