// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LMSProje.Models;

[Table("tblCategory")]
public partial class TblCategory
{
    [Key]
    public int CategoryId { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string CategoryName { get; set; }

    [InverseProperty("Category")]
    public virtual ICollection<TblBooks> TblBooks { get; set; } = new List<TblBooks>();
}