// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LMSProje.Models;

[Table("tblRecords")]
public partial class TblRecords
{
    [Key]
    public int RecordId { get; set; }

    public int BookId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime AcquisitionDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ReturnDate { get; set; }

    [ForeignKey("BookId")]
    [InverseProperty("TblRecords")]
    public virtual TblBooks Book { get; set; }

    [InverseProperty("Record")]
    public virtual ICollection<TblAdminApporoval> TblAdminApporoval { get; set; } = new List<TblAdminApporoval>();

    [ForeignKey("UserId")]
    [InverseProperty("TblRecords")]
    public virtual TblUser User { get; set; }
}